<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;

class BaseController extends \yii\web\Controller
{
    public function beforeAction($action)
    {

        $allowed = [
            'hero-selection',
            'logout',
        ];

        if (!Yii::$app->user->isGuest && !in_array($this->action->id, $allowed)) {
            if (empty(Yii::$app->user->identity->hero_id)) {
                $this->redirect('/hero/hero-selection');
            }
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}