<?php
namespace common\components\web;

use common\widgets\Alert;
use Yii;
use yii\web\Response;

class Controller extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        $allowed = [
            'hero-selection',
            'logout',
        ];

        if (!Yii::$app->user->isGuest && !in_array($this->action->id, $allowed)) {
            if (empty(Yii::$app->user->identity->hero_id)) {
                $this->redirect('/hero/hero-selection');
            }
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $view
     * @param array $params
     * @return \yii\web\Response
     */
    public function answer(string $view, array $params = [])
    {
        $response = Yii::$app->response;
        if (Yii::$app->request->isAjax && !Yii::$app->request->isPjax) {
            $replace = $_GET['replace'] ?? false;
            if (!$replace && !isset($params['isAjax'])) {
                $params['isAjax'] = true;
            }

            $response->format = Response::FORMAT_JSON;
            $response->data['html'] = $this->renderPartial($view, $params);
        } else {
            $response->format = Response::FORMAT_HTML;
            $response->data = $this->render($view, $params);
        }

        return $response;
    }

    /**
     * @param array|string $url
     * @return \yii\web\Response
     */
    public function conclude($url)
    {
        $response = Yii::$app->response;
        if (Yii::$app->request->isAjax && !Yii::$app->request->isPjax) {
            $response->format = Response::FORMAT_JSON;
            $response->data['message'] = Alert::widget();
        } else {
            $response->redirect($url);
        }

        return $response;
    }
}
